---
repos:
  # See https://pre-commit.com for more information
  # See https://pre-commit.com/hooks.html for more hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # - repo: https://github.com/frnmst/md-toc.git
  #   rev: "master" # or a specific git tag from md-toc
  #   hooks:
  #     - id: md-toc
  #       args: ["-p", "github", "-l6"] # CLI options
  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint-docker
